[package]
name = "chip8"
version = "0.1.0"
authors = ["Jeyko Caicedo <jakeactually@outlook.com>"]

[dependencies]
piston_window = "0.107.0"
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
